# Game constants
WIDTH, HEIGHT = 800, 600
CUBE_SIZE = 20
PADDLE_SPEED = 4
BALL_SPEED = 10
POINTS_TO_WIN = 5
MAX_FRAMES_PER_GAME = 5000

# Paddle dimensions
PADDLE_WIDTH = 20
PADDLE_HEIGHT = 100
PADDLE_HALF_H = PADDLE_HEIGHT // 2

# Paddle positions
PADDLE_LEFT_X = 50
PADDLE_RIGHT_X = WIDTH - PADDLE_LEFT_X - PADDLE_WIDTH